# Generated by Django 4.0.8 on 2022-10-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
